name: Continous Integration

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

env:
  JAVA_VERSION: 24
  POSTGRES_USER: ${{secrets.POSTGRES_USER}}
  POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
  POSTGRES_PORT: 5432
  POSTGRES_DB: hackernews
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/hackernews

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:25.0.0
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK ${{env.JAVA_VERSION}}
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: ${{env.JAVA_VERSION}}
          cache: gradle
      - name: Grant execute permission for Gradle Wrapper
        run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew build --stacktrace --info